
== How to demo Application Services with Solution Patterns

Solution Patterns help you to demonstrate how *Red Hat Application Platform + Red Hat Portfolio* can solve common scenarios and use cases for your customers and partners.

Each Solution Pattern contains public documentation of the architectural solution, use cases, challenges, detailed explanation,  actual implementation, fully reproducible. 

With these patterns you can

* *learn* hands-on Red Hat technologies based on real world use cases
* use them as part of your customer discussions to *demonstrate* the full capabilities of Red Hat technologies 
* run technical *workshops* for your customers including handson labs for developers


== Workshop goals

The primary goal of this workshop is to guide you through a couple of selected sections of the a couple of following solution patterns so that you can try these out yourself, and undertsand how to use these patterns to demostrate Red Hat Application Services with your customers. Each of these labs are part of a more complete Solution Pattern, and can be accessed via their respective pages

The solution patterns for this workshop are based on retail use cases based on a fictitious customer. 

* Modernize an existing application with Change Data Capture
* Extend applications to adopt Event Streaming capabilities using Red Hat Application Services

You will learn more about the background of each of the usecases in the next sections.

We welcome your feedback on what works and what doesn't, and also very importantly we invite you to be a part of and contribute to the open community of Red Hat Solution Patterms.

In the next step you will setup a few prerequistes needed to perform the labs.